[[copt]]
arch = "aarch64"
os = "linux"
git-tree-sha1 = "89a3cfd5250e3a544f4a9fc14d625db70cbbf164"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.2/aarch64/CardinalOptimizer-8.0.2-aarch64_lnx.tar.gz"
    sha256 = "76f36d38be6b3c60cd8f9e7e22363b142fdf03883937edccb45e714e7a22a3ff"

[[copt]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "4f3c07d1a34eecd869ac885f1eec03fa11f1dce5"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.2/osx64/CardinalOptimizer-8.0.2-universal_mac.tar.gz"
    sha256 = "6c0919e54621ca2545cc6ff783467c2df56a38feaa73d3e2ba26f6996c72a157"

[[copt]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "31c1e092d828f0d412a95986219cb2d89c745b79"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.2/linux64/CardinalOptimizer-8.0.2-lnx64.tar.gz"
    sha256 = "bb984c926dfcb711d6eeb78617d46146052280717515df75dc99b0c8d017dab2"

[[copt]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "4f3c07d1a34eecd869ac885f1eec03fa11f1dce5"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.2/osx64/CardinalOptimizer-8.0.2-universal_mac.tar.gz"
    sha256 = "6c0919e54621ca2545cc6ff783467c2df56a38feaa73d3e2ba26f6996c72a157"

[[copt]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "b404f68a0cd67061353b910b3e3e4f40c8953842"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.2/win64/CardinalOptimizer-8.0.2-win64.tar.gz"
    sha256 = "9df30c165ba87c655959db8524cb839ea6877a88849b2b4a7c3f48e16508a71f"

