[[copt]]
arch = "aarch64"
os = "linux"
git-tree-sha1 = "dab950c26237d94434950392c026b6c16b3b3be9"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.1/aarch64/CardinalOptimizer-8.0.1-aarch64_lnx.tar.gz"
    sha256 = "903b413cb3abacdcde10744f27733feda26ddac2ad2df77a3e4793c89d8916b7"

[[copt]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "2b740c31a6c977bb65243987f0e9ba6cbda55b18"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.1/osx64/CardinalOptimizer-8.0.1-universal_mac.tar.gz"
    sha256 = "2850438c1a564d41912a05a3692c2b4cf5bf5d8ed5266850c0398cf2510f5d21"

[[copt]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "f9ec21c2b6bab359c0b82ba06d22f853657d6d7c"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.1/linux64/CardinalOptimizer-8.0.1-lnx64.tar.gz"
    sha256 = "117d7cb42d5677359dbb144ba29d2296b39e0dbea024b15c856bef6498adbd8b"

[[copt]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "2b740c31a6c977bb65243987f0e9ba6cbda55b18"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.1/osx64/CardinalOptimizer-8.0.1-universal_mac.tar.gz"
    sha256 = "2850438c1a564d41912a05a3692c2b4cf5bf5d8ed5266850c0398cf2510f5d21"

[[copt]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "b1d643a647aa721986a39a023c1adbeef039c15d"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.1/win64/CardinalOptimizer-8.0.1-win64.tar.gz"
    sha256 = "8d2562931ab878435cfbb3c56ea8fc2eb39d3749c61b9d73f01c1aac09f3e251"

